* Guix channel for Doom Emacs
** Packages
- =doomemacs=, =doomemacs-modules=
- assorted emacs packages used by doomemacs-modules

** Services
- =home-doomemacs-service-type=

** Examples
- [[./example/home.scm]] installs the example config shipped with doom
- [[./example/home-org.scm]] shows how to make a literate-style config

Give it a try:
#+begin_src sh
guix home -L ./src container example/home.scm -- env TERM=rxvt emacs -nw
#+end_src
** Migrating your existing config
See the examples above. Start with a minimal configuration.
#+begin_src scheme
(doomemacs-configuration
 (emacs emacs-next-pgtk)                ; your flavor of choice
 (doomemacs doomemacs)                  ; that's the core

 ;; here goes your existing doom.d containing init.el, config.el, packages.el
 ;; and maybe your modules
 (config (local-file "doom.d" #:recursive? #t))
 ;; start with the default modules first
 (inputs (list doomemacs-modules)))
#+end_src

Building this configuration will fail, because of missing =inputs= - emacs
packages that your configuration uses. Check the build log file, the list of
dependencies will be printed under the =MISSING PACKAGES= message. Copy this list
to the =inputs= field. Some packages might be missing from both guix in this
channel. In that case find the definitons on https://toys.whereis.social/ or
write your own.

** Design choices
- no pinning by default - guix packages used as is
- when doom breaks because of an outdated package - pin in your config and bump the package in guix
** TODO Things to do [0/2]
- [ ] improve the service
  - get rid of activation script - add glue code to doom package that loads profiles generated by guix
  - fix =doom doctor= and friends 
- [ ] add tests / ci scripts
  - ensure no breakage after bumping packages or base guix channel
