;;; build-profile.el --- Generates doom's startup file. -*- lexical-binding: t; -*-
(letf!
  ((doom-module-load-path (split-string (getenv "DOOM_MODULE_PATH") ":" t))
   (defun! doom-initialize-core-packages (&optional force-p)
     (message "Inhibiting core packages initialization"))

   (defun! doom-profile--add-modules-from-guix (_profile)
     (doom-file-write
      "15-user.init.el"
      `((setq doom-module-load-path
              (list ,@doom-module-load-path))))))
  
  (setq doom-profile-generate-functions
        '(doom-profile--generate-init
          doom-profile--generate-loaddefs-doom
          doom-profile--add-modules-from-guix
          doom-profile--generate-user-init-loader
          doom-profile--generate-package-envs
          ;; duplicates site-start.el generated by guix
          ;; doom-profile--generate-loaddefs-packages
          doom-profile--generate-loaddefs-modules
          doom-profile--generate-module-loader))

  (doom-modules-initialize)
  (setq doom-packages (doom-package-list))
  (let ((missing-pkgs '()))
    (dolist (package doom-packages)
      (cl-destructuring-bind
          (name &key disable ignore &allow-other-keys) package

        (when disable
          (cl-pushnew name doom-disabled-packages))
        (unless (or disable ignore (eq 'straight name) (locate-library (symbol-name name)))
          (cl-pushnew (concat "\"emacs-" (symbol-name name) "\"") missing-pkgs))))
    (when missing-pkgs
      (message "!!!!! MISSING PACKAGES !!!!!")
      (mapc 'message (sort missing-pkgs))
      (setq backtrace-on-error-noninteractive nil)
      (error "Please add missing packages to inputs of doomemacs-configuration %s" missing-pkgs)))

  (doom-profile-generate))
